BEGIN TRANSACTION;
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Super Bear Adventure', 'https://arbcdn.techfast.vn/514e1e1d61bb41f290f9bbc1e275d08b.webp', 'Super Bear Adventure delivers a delightful 3D platformer with its vibrant worlds and heroic quest, celebrating a family-friendly adventure.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Zenless Zone Zero', 'https://arbcdn.techfast.vn/d021c85e88874fce82f66100cea0c70f.webp', 'Zenless Zone Zero delivers a stylish action RPG with its exhilarating combat and cyberpunk world, celebrating a unique urban fantasy.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Roblox: Plants Vs Brainrots', 'https://arbcdn.techfast.vn/41da3764c736460aab64934a0aa73130.webp', 'Roblox: Plants Vs Brainrots delivers a whimsical tower defense adventure with its meme-inspired combat and garden growth, celebrating a unique Roblox twist.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Delta Force', 'https://arbcdn.techfast.vn/85007010fc51494bb913369ac8085473.webp', '"Delta Force" remains a significant title in the history of first-person shooters, setting the stage for tactical gameplay in a genre often dominated by fast-paced action.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'UFL™', 'https://arbcdn.techfast.vn/14b7c81ab6304539881b343b8926a305.webp', 'UFL™ delivers a promising soccer simulation with its skill-based gameplay and global leagues, celebrating a fair-play approach. Its squad management and matches shine, though animations and technical issues pose challenges.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'LEGO® Voyagers', 'https://arbcdn.techfast.vn/523cfb177b9c4362af70eba08e3a4a3c.webp', 'LEGO® Voyagers captures the magic of LEGO by blending cooperation, creativity, and humor into a family friendly adventure.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Blood Strike', 'https://arbcdn.techfast.vn/d8e1498763e84a7da306a8a0ee96d6a0.webp', 'Blood Strike delivers a thrilling mobile battle royale experience with its fast-paced combat and squad dynamics, celebrating a unique shooter twist.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Borderlands 4', 'https://arbcdn.techfast.vn/6321da3240754dca8449d7007087f4fa.webp', 'Borderlands 4 delivers a chaotic looter-shooter adventure with its vast world and hilarious combat, celebrating the series’ signature absurdity.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Roblox: RIVALS', 'https://arbcdn.techfast.vn/9fa9a9ccef85458a8bbb3003f608cd32.webp', 'Roblox: RIVALS delivers an exhilarating FPS experience with its intense duels and vibrant design, celebrating a unique Roblox shooter twist.'),
((SELECT id FROM games_page WHERE page_index=1 LIMIT 1), 'Monument Valley', 'https://arbcdn.techfast.vn/41fea8f31089474dbd03122ea1deff01.webp', 'Monument Valley delivers a serene puzzle adventure with its stunning art and gentle challenges, celebrating a unique mobile experience.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'PEAK', 'https://arbcdn.techfast.vn/ac876c3b5cad40f78b7c33327eaceba1.webp', 'PEAK delivers a thrilling cooperative survival adventure with its dynamic climbs and team spirit, celebrating the joy of scaling together.'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Roblox 99 Nights In The Forest', 'https://arbcdn.techfast.vn/8258ff65d45f41ce9fdf58e16a5a58b8.webp', 'Roblox: 99 Nights in the Forest is a compelling survival-horror experience that has raised the bar for what Roblox games can deliver'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Lost & Found: The Boring Game', 'https://arbcdn.techfast.vn/b5a41df7224746a08f22b900d3ac95d4.webp', 'Lost & Found: The Boring Game stands out by turning a mundane scenario into a motivator for fast, strategic decision-making with a dash of moral ambiguity'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Avatar World', 'https://arbcdn.techfast.vn/288b5ac50db64d05ab4f8187b7c4c0e6.webp', 'Avatar World is a cheerful, creativity-driven sandbox that succeeds as a digital dollhouse for kids'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Grand Theft Auto: San Andreas', 'https://arbcdn.techfast.vn/f6acce16fa74453cbd73341a23e0ca1e.webp', 'Grand Theft Auto: San Andreas is more than just a game; it’s a cultural landmark. Its bold storytelling, vast open world, and revolutionary mechanics defined an era and continue to inspire modern developers'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Rematch', 'https://arbcdn.techfast.vn/363c2f9bc8a54660b75d6d1bd467771d.webp', 'A creatively daring and mechanically rewarding football experience with untapped potential — provided Sloclap resolves performance and content gaps soon.'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Roblox: Grow a Garden', 'https://arbcdn.techfast.vn/7da624be8be3426da3805b09cc5c25c2.webp', 'Roblox: Grow a Garden offers a refreshing, slower-paced take on Roblox gameplay, where patience, creativity, and community are more important than reflexes or competition'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'Brawl Stars', 'https://arbcdn.techfast.vn/a9d03c8ff9df42fb9d4925e66b60931e.webp', 'Brawl Stars is a prime example of how to design a mobile-first competitive game that remains fun in both casual and hardcore contexts'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'NBA 2K24', 'https://arbcdn.techfast.vn/5a853dde84f34a29a8f3f5716c1b2c09.webp', 'NBA 2K24 is both a technical achievement and a polarizing product. On one hand, ProPLAY technology, deep modes, and the tribute to Kobe Bryant make it a standout entry in the franchise'),
((SELECT id FROM games_page WHERE page_index=10 LIMIT 1), 'The Legend of Zelda', 'https://arbcdn.techfast.vn/7593c75027364a6fabc92ca413ed1b4b.webp', 'The Legend of Zelda is more than a franchise — it is a blueprint for adventure gaming itself');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Valorant', 'https://arbcdn.techfast.vn/cc4d406ff04d46d5b63cd4c24b1566a2.webp', 'Valorant is Riot Games’ bold attempt to redefine the tactical FPS genre — and it has succeeded'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Free Fire Max x NARUTO', 'https://arbcdn.techfast.vn/44fd84320eed40139223d811b4154fde.webp', 'Free Fire MAX successfully redefines Garena’s battle royale identity for the modern mobile era'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Gacha Club', 'https://arbcdn.techfast.vn/4d450c49627d4f23a13aac7fb2264a16.webp', 'Gacha Club is a free anime-style game where you create characters, design scenes in Studio Mode, and battle with teams in various modes. With no ads or purchases, it’s perfect for creative fun and safe for all ages'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Sonic the Hedgehog™ Classic', 'https://arbcdn.techfast.vn/1fd89865cd1c4314ad0c2cbcaf93bfc5.webp', 'Sonic the Hedgehog™ Classic is a 1991 platformer for the Sega Genesis where players control Sonic, a speedy blue hedgehog, as he navigates vibrant levels filled with obstacles and enemies. Featuring iconic zones like Green Hill Zone and intense boss fights against Dr. Robotnik, the game is celebrated for its colorful graphics and catchy soundtrack. As a cultural icon, Sonic has influenced numerous sequels and adaptations, solidifying its place in gaming history.'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Fall Guys: Ultimate Knockout', 'https://arbcdn.techfast.vn/bda00873d8314361a4d75856e94142aa.webp', 'Explore the fun and frenzy of Fall Guys — a hilarious battle royale packed with wild obstacle courses, seasonal events, tips, skins, and non-stop chaotic competition.'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Genshin Impact', 'https://arbcdn.techfast.vn/cc2c1a896d3b48fc8a2255afb923f248.webp', 'Genshin Impact is an open-world RPG where you explore Teyvat, master elemental combat, and uncover the story of the Traveler across seven diverse nations.'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Geometry Dash', 'https://arbcdn.techfast.vn/c9eed900d6154a1e918edf013a3f5469.webp', 'Geometry Dash is a fast-paced rhythm platformer with addictive gameplay, and creative tools that keep players coming back for more.'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'Steal a Brainrot Roblox', 'https://arbcdn.techfast.vn/e35efdaac0cc440f9a3a49ead1e07db0.webp', 'A chaotic, addictive tycoon that thrives on social interaction and emotional investment — both a playground and a battlefield for Roblox players.'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'EA SPORT FC 25', 'https://arbcdn.techfast.vn/8f53f658141344b58e9e4021ebea02d8.webp', 'EA SPORTS FC 25 earns its keep by changing how you think about your team, not just how you time your green-timed shots'),
((SELECT id FROM games_page WHERE page_index=11 LIMIT 1), 'FIFA 23', 'https://arbcdn.techfast.vn/17c1769a557244f08902bc8c42429d05.webp', 'FIFA 23 is not just the end of an era — it’s a confident send-off that consolidates EA’s football dominance while signaling the future of connected, live-service sports gaming.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'League of Legends: Wild Rift', 'https://arbcdn.techfast.vn/256b50350faf4a6092597488b78070af.webp', 'Wild Rift isn’t just “LoL on mobile” — it’s a carefully engineered sibling title that can stand on its own in the mobile MOBA arena.'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Toca Boca World', 'https://arbcdn.techfast.vn/a2fdfd32e29d4c4c8c276173af43bb9f.webp', 'A gold-standard sandbox for imaginative play—thoughtfully safe, beautifully crafted, and sustainably expandable.'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Free Fire x NARUTO SHIPPUDEN', 'https://arbcdn.techfast.vn/c12e0614376848ef91051cdce33791bf.webp', 'Free Fire is proof that in mobile gaming, accessibility and adaptability can outweigh pure graphical fidelity — especially when paired with aggressive live-service execution.'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Gorilla Tag', 'https://arbcdn.techfast.vn/b038826fd0d64ac5b21aea709ae9fd10.webp', 'Gorilla Tag is a unique VR game with arm-based movement, fast-paced tag gameplay, a creative community, and lively social interaction'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'BeamNG.drive', 'https://arbcdn.techfast.vn/f152754a19b74654810c9aa276f6f25a.webp', 'BeamNG.drive is the definitive playground for anyone fascinated by vehicles, physics, or the art of controlled (and uncontrolled) destruction'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Among Us', 'https://arbcdn.techfast.vn/599ab20bf2984fffa6aa7d888b4a37f9.webp', 'Among Us is less about game mechanics and more about human interaction — and that’s exactly why it became a global sensation'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Poppy Playtime', 'https://arbcdn.techfast.vn/cbec5ff109ce464b9256e6e7bea9669a.webp', 'Poppy Playtime proves that with the right mix of distinctive characters, lore depth, and viral design, an indie title can compete in the global horror space alongside much bigger-budget productions'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Grand Theft Auto V', 'https://arbcdn.techfast.vn/7e84e0f737e0442ea9118c00da72c42f.webp', 'Grand Theft Auto V delivers a legendary open-world adventure with its expansive world and cinematic storytelling, celebrating a unique action experience.'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'League of Legends', 'https://arbcdn.techfast.vn/6f15b26d8b344201bbe6ac609c123641.webp', 'League of Legends is more than a game — it’s a global phenomenon and a living blueprint for sustained multiplayer success'),
((SELECT id FROM games_page WHERE page_index=12 LIMIT 1), 'Candy Crush Saga', 'https://arbcdn.techfast.vn/610ac47241d748569470c877a11a4114.webp', 'Candy Crush Saga proves that you don’t need cutting-edge graphics or complex mechanics to dominate mobile gaming — you just need to master player psychology and live-service execution');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=13 LIMIT 1), 'Roblox', 'https://arbcdn.techfast.vn/1a04b52e353e451d9f16af4704a40342.webp', 'Roblox is not just a game — it’s a platform that has redefined what it means to play, create, and earn in the digital age'),
((SELECT id FROM games_page WHERE page_index=13 LIMIT 1), 'Fortnite: Mobile Battle Royale', 'https://arbcdn.techfast.vn/942c431d1a3c4779b8b307568e913916.webp', 'Fortnite isn’t just surviving in the competitive battle royale space — it’s defining it'),
((SELECT id FROM games_page WHERE page_index=13 LIMIT 1), 'Minecraft', 'https://arbcdn.techfast.vn/811c9ee3c2344d7b81b27b1d09f9231b.webp', 'Minecraft is both timeless and ever-evolving — a rare combination that ensures its place in gaming’s cultural DNA'),
((SELECT id FROM games_page WHERE page_index=13 LIMIT 1), 'PUBG Mobile', 'https://arbcdn.techfast.vn/dd7f0bdc64854d0eaffbee03e36c313f.webp', 'PUBG Mobile remains a must-play for battle royale enthusiasts and a fascinating case study for game developers and analysts alike');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Drive Beyond Horizons', 'https://arbcdn.techfast.vn/4a2edf6826284f9698b7fa31b4872726.webp', 'Drive Beyond Horizons delivers a rugged survival adventure with its open-world exploration and vehicle customization, celebrating the thrill of the unknown.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Call of Duty®: Black Ops 7', 'https://arbcdn.techfast.vn/5d706cb66ac74a9ab54dd5d835373d2e.webp', 'Call of Duty®: Black Ops 7 delivers an exhilarating FPS adventure with its co-op campaign and expansive modes, celebrating the Black Ops legacy.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Warhammer 40,000: Speed Freeks', 'https://arbcdn.techfast.vn/e598357aeb564cf5acea88b7218b7f6a.webp', 'Warhammer 40,000: Speed Freeks delivers a chaotic vehicular combat-racing adventure with its Orkish mayhem and creative tools, celebrating the Speedwaaagh!'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Garfield Kart 2 - All You Can Drift', 'https://arbcdn.techfast.vn/9f045cdf0336421dba3569eb3028cf25.webp', 'Garfield Kart 2 - All You Can Drift delivers a fun kart racing adventure with its vibrant tracks and multiplayer chaos, celebrating Garfield’s return to the raceway.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Roblox: Blox Fruits', 'https://arbcdn.techfast.vn/471726413b464bbc980cd3c7622608fa.webp', 'Blox Fruits delivers a thrilling action-adventure on Roblox with its diverse combat and social gameplay, celebrating the quest for power.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Hollow Knight: Silksong', 'https://arbcdn.techfast.vn/22b2eb32ddc54fee9d2de6bbe4088794.webp', 'Hollow Knight: Silksong delivers a mesmerizing metroidvania adventure with its intricate world and challenging combat, celebrating the journey of Hornet.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Totally Accurate Battle Simulator', 'https://arbcdn.techfast.vn/aedacfbbf0754a6180953053a9370e69.webp', 'Totally Accurate Battle Simulator (TABS) delivers a hilarious battle simulation with its creative chaos and multiplayer appeal, celebrating the joy of wobbly warfare.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Hades', 'https://arbcdn.techfast.vn/86de9e419a0842bbb0c3a5db7b20d7b5.webp', 'Hades delivers a thrilling roguelike adventure with its engaging combat and rich narrative, celebrating the escape from the Underworld.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'TUNIC', 'https://arbcdn.techfast.vn/2399682291fc4b979f2ed207a6b21d63.webp', 'TUNIC delivers a mesmerizing metroidvania adventure with its atmospheric world and clever puzzles, celebrating the joy of discovery.'),
((SELECT id FROM games_page WHERE page_index=2 LIMIT 1), 'Hollow Knight', 'https://arbcdn.techfast.vn/a122572e935f41de9703ec42b31c5b31.webp', 'Hollow Knight delivers a mesmerizing metroidvania adventure with its challenging gameplay and atmospheric world, celebrating the thrill of exploration.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Stardew Valley', 'https://arbcdn.techfast.vn/871eb7017960449e8e75f78d11fab816.webp', 'Stardew Valley delivers a heartwarming farming simulation with its rich gameplay and community charm, celebrating the joy of rural life.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Merge Fellas', 'https://arbcdn.techfast.vn/29d17ba6a8cc4fefa4b1403c2d4eb134.webp', 'Merge Fellas delivers a charming merge puzzle adventure with its creative gameplay and mode diversity, celebrating the joy of combining characters.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Mecha Break', 'https://arbcdn.techfast.vn/08f471c2e7944919bd06cd2c2af1b97d.webp', 'Mecha Break delivers a thrilling hero shooter with its fast-paced combat and mech diversity, celebrating the joy of piloted warfare.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Roblox: Garden Tower Defense', 'https://arbcdn.techfast.vn/c9844d0372524260a8027653394909a9.webp', 'Roblox: Garden Tower Defense delivers a captivating tower defense adventure with its strategic gameplay and community-driven trading, celebrating the joy of garden protection.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Mafia: The Old Country', 'https://arbcdn.techfast.vn/1e30bd47a5154fe59814d46b487fdc58.webp', 'Mafia: The Old Country delivers a gripping action-adventure with its cinematic storytelling and intense gameplay, celebrating the mafia’s origins.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'My Talking Tom Friends 2', 'https://arbcdn.techfast.vn/ab81db361c104f29a71d4495a421e0e2.webp', '"My Talking Tom Friends 2" successfully blends simulation, creativity, and social interaction in a delightful mobile experience.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'FIFA Rivals - Mobile Football', 'https://arbcdn.techfast.vn/1f19a5561ff54a73a4f136a0d82a572f.webp', '"FIFA Rivals - Mobile Football" successfully captures the essence of football in a mobile format, combining team management, real-time gameplay, and competitive features.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Car Driving 2025 : School Game', 'https://arbcdn.techfast.vn/9e6fd980e231482994799469cb2fae99.webp', '"Car Driving 2025: School Game" successfully blends entertainment with education, offering a unique driving experience that appeals to a wide audience.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Dress to Impress', 'https://arbcdn.techfast.vn/655af97a62d94401aa37e28684c476fc.webp', '"Dress to Impress" successfully combines creativity, competition, and social interaction in a visually captivating environment.'),
((SELECT id FROM games_page WHERE page_index=3 LIMIT 1), 'Little Nightmares II', 'https://arbcdn.techfast.vn/5e2ed27ec7534567925a396534fb0804.webp', 'Little Nightmares II delivers a chilling puzzle adventure with its atmospheric storytelling and tense gameplay, celebrating the horror of survival.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Grounded 2', 'https://arbcdn.techfast.vn/04a7e7cbd80d4a13aef707ef1652fda6.webp', 'Grounded 2 represents a significant evolution in the survival genre, building on the strengths of its predecessor while addressing its limitations.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Adopt Me!', 'https://arbcdn.techfast.vn/55005bf8df1546cf9398351c14d7cdfe.webp', 'Adopt Me! delivers a vibrant social simulation with its pet-raising mechanics and community-driven roleplay, celebrating the joy of virtual adoption.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'eFootball™', 'https://arbcdn.techfast.vn/b952cfd9afb24a6ea575e9ddce48a120.webp', 'eFootball™ represents a new chapter in the world of football video games, aiming to provide an engaging experience for players.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Marvel’s Spider-Man: Miles Morales', 'https://arbcdn.techfast.vn/d5f36a80419e473b97c11b5329c7f34a.webp', 'Marvel''s Spider-Man: Miles Morales delivers a thrilling superhero adventure with its engaging story and web-slinging mastery, celebrating Miles’ rise to heroism.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Destiny 2', 'https://arbcdn.techfast.vn/9a56debc4f834bcd8494967bac597afe.webp', 'Destiny 2 is a game that has grown and evolved since its initial release, offering players a vast universe filled with engaging gameplay, rich lore, and a vibrant community.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Last War: Survival', 'https://arbcdn.techfast.vn/328a32abacd84f8998b0f2989318d644.webp', 'Last War: Survival delivers a strategic survival epic with its alliance-driven gameplay and hero diversity, celebrating the thrill of post-apocalyptic teamwork.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'EA SPORTS™ College Football 26', 'https://arbcdn.techfast.vn/216f96b60a9b41989dfa51805e68ad35.webp', 'EA SPORTS™ College Football 26 offers a vibrant celebration of college football with enhanced rivalries and Dynasty mode, capturing the sport’s unique spirit.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'F1® 25', 'https://arbcdn.techfast.vn/802459d512b94c73b950e0fc10b87ee7.webp', 'F1® 25 delivers a refined racing experience with enhanced handling and a compelling Braking Point story, building on the series’ strengths.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'Battlefield™ 6', 'https://arbcdn.techfast.vn/321595c15d114638924d084823c8c669.webp', 'Battlefield™ 6 delivers a thrilling return with epic scale and innovative combat, rivaling the franchise’s best moments.'),
((SELECT id FROM games_page WHERE page_index=4 LIMIT 1), 'EA SPORTS™ Madden NFL 26', 'https://arbcdn.techfast.vn/5a829aebd75745c185e112ae74596642.webp', 'Madden NFL 26 delivers a robust football sim with enhanced gameplay and Franchise depth, rivaling past highs.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Tsuki''s Odyssey', 'https://arbcdn.techfast.vn/2dd62ca214a742c6957c7c6523a3ec64.webp', 'Tsuki''s Odyssey offers a cozy idle adventure with delightful customization and a relaxing pace, perfect for short breaks.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Gacha Life', 'https://arbcdn.techfast.vn/d3ee573daab84d5093a54a74db0a0145.webp', 'Gacha Life offers a vibrant creative sandbox for young players, excelling with its customization and community engagement.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Call of Duty®: Warzone™ 2.0', 'https://arbcdn.techfast.vn/b604f981b9ff497096700bea62d5a159.webp', 'Call of Duty®: Warzone™ 2.0 doesn’t just re-skin the original; it redefines what the Warzone experience can be.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Call of Duty®: Warzone™ Mobile', 'https://arbcdn.techfast.vn/8d2d20f1e93c4c1d941f4a3697b305ea.webp', 'Call of Duty®: Warzone™ Mobile is one of the most ambitious mobile shooters ever released.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Call of Duty®: Modern Warfare® III', 'https://arbcdn.techfast.vn/9e6b4703e62a4289a1d7406de2a5cdc7.webp', 'Call of Duty®: Modern Warfare® III successfully builds on the foundation of its predecessor, delivering a fast-paced shooter that combines narrative intensity with a massive multiplayer offering.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Call of Duty®: Modern Warfare® II', 'https://arbcdn.techfast.vn/cb940a62facd40b8918a0a2233aa5b9a.webp', 'Call of Duty®: Modern Warfare® II is a bold, cinematic, and highly polished entry that successfully pushes the franchise forward.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Call of Duty®: Vanguard', 'https://arbcdn.techfast.vn/ffd771d265b94444bd6c14df1ad75a4a.webp', 'Call of Duty®: Vanguard is a solid but somewhat safe entry in the long-running franchise.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Poppy Playtime - Chapter 4', 'https://arbcdn.techfast.vn/c9ccb2523a8c4e13af0c7139dc79d39e.webp', 'Poppy Playtime – Chapter 4: Shadows of Play is shaping up to be the most ambitious installment yet.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Poppy Playtime - Chapter 3', 'https://arbcdn.techfast.vn/7c3333dd51eb4c14b55307c8b5f9f44d.webp', 'Poppy Playtime – Chapter 3: Deep Sleep represents a major step forward for the series.'),
((SELECT id FROM games_page WHERE page_index=5 LIMIT 1), 'Poppy Playtime - Chapter 2', 'https://arbcdn.techfast.vn/f31b0957f32a41f083823e2d6f63fc7a.webp', 'Poppy Playtime: Chapter 2 successfully expands the series, delivering bigger scares, smarter puzzles, and one of horror gaming’s most memorable new villains in Mommy Long Legs.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Monsters & Mortals - Poppy Playtime Panic DLC', 'https://arbcdn.techfast.vn/92921e57954c46d5ab37494abf9d3f69.webp', 'The Poppy Playtime Panic DLC is a must-play for fans of both franchises. It brings recognizable characters and environments from Poppy Playtime into the chaotic multiplayer horror arena of Monsters & Mortals without losing the essence of either game.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Escape from Tarkov', 'https://arbcdn.techfast.vn/c09c2b7c2b0b45859223a459a2048553.webp', 'Escape from Tarkov delivers a hardcore survival FPS adventure with its realistic combat and deep progression, celebrating a unique tactical experience.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'inZOI', 'https://arbcdn.techfast.vn/331efd35d3e9457db80ab9e3ca2a90e5.webp', 'inZOI offers a visually stunning life sim with deep customization, bolstered by Island Getaway’s fresh content, challenging The Sims’ throne.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'The Headliners', 'https://arbcdn.techfast.vn/09182ad05172417eb3d557c95e8b6c58.webp', 'The Headliners delivers a thrilling co-op horror adventure with its dark humor and team-based action, celebrating a unique journalistic twist.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Splitgate 2', 'https://arbcdn.techfast.vn/5f7165b57dd9468fb9d25644c805cb1f.webp', 'Splitgate 2 delivers a thrilling arena shooter experience with its innovative portals and fluid movement, celebrating a unique combat twist.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Sonic Rumble', 'https://arbcdn.techfast.vn/4ef2c94c413e4f548f778921f92016a5.webp', 'Sonic Rumble delivers a thrilling multiplayer party experience with its innovative portals and Sonic charm, celebrating a unique battle royale twist.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Subway Surfers', 'https://arbcdn.techfast.vn/85644e90524741d984ba006bb3f98454.webp', 'Subway Surfers remains a mobile gaming icon, delivering addictive runs with vibrant visuals and power-ups, perfect for casual play.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'R.E.P.O.', 'https://arbcdn.techfast.vn/e78ce9d224384adc8a0ec70266329423.webp', 'R.E.P.O. offers a gripping cooperative horror experience with its physics-based gameplay and monster diversity, celebrating the thrill of teamwork under pressure.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Five Nights at Freddy''s', 'https://arbcdn.techfast.vn/907e52c686454e008567fd5fdbcc9c73.webp', 'Five Nights at Freddy''s remains a groundbreaking indie horror classic, delivering tense survival and atmospheric dread through its innovative power-management mechanic and jump scares.'),
((SELECT id FROM games_page WHERE page_index=6 LIMIT 1), 'Into the Dead: Our Darkest Days', 'https://arbcdn.techfast.vn/add4c203397f455ca079d844147291f0.webp', 'Into the Dead: Our Darkest Days delivers a thrilling survival horror experience with its tense atmosphere and strategic gameplay, celebrating a unique 1980s zombie twist.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'PARANOIA PLACE', 'https://arbcdn.techfast.vn/61bc5328d6e6445588850b661d6c837a.webp', 'PARANOIA PLACE stands as a compelling indie survival horror gem, particularly for co-op fans craving tense, voice-chat-driven escapes from a demonic foe.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'House of Lost Souls', 'https://arbcdn.techfast.vn/eb43b38c44e048da8a2970648e913a05.webp', 'House of Lost Souls is a haunting, if flawed, psychological horror experience that excels in atmosphere and emotional storytelling but stumbles with technical issues and limited gameplay depth.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Blue Prince', 'https://arbcdn.techfast.vn/d043c23b20404e27849e2eea4fc6ba5b.webp', 'Blue Prince is a genre-defying masterpiece that blends roguelike strategy, puzzle-solving, and narrative mystery into an unforgettable experience.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'The Sims™ 4', 'https://arbcdn.techfast.vn/e7444d3686444523a2d9c8af84531efe.webp', 'The Sims™ 4 is a captivating life simulator that excels in creativity, customization, and emotional storytelling, offering endless possibilities for builders and storytellers.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Look Outside', 'https://arbcdn.techfast.vn/ea980a1d126c4251bd69440b2bb34bdf.webp', 'Look Outside is a hauntingly brilliant indie horror RPG that blends retro aesthetics with modern psychological dread.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Zoonomaly', 'https://arbcdn.techfast.vn/0b88fb2050c0445ea6f0e46d8a4f5420.webp', 'Zoonomaly is a compact, puzzle-driven indie horror game that delivers a strong sense of atmosphere and tension.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Guilty as Sock!', 'https://arbcdn.techfast.vn/cd882199364d4358986c1f66ea3e666c.webp', 'Guilty as Sock! delivers a hilarious party game experience with its absurd trials and cooperative chaos, celebrating a unique sock puppet twist.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Sonic Racing: CrossWorlds', 'https://arbcdn.techfast.vn/f87d6fd357764d05b293dfc6e392c6bd.webp', 'Sonic Racing: CrossWorlds is Sega’s most ambitious racing project yet, blending Sonic’s speed with creative mechanics and a surprisingly narrative-driven campaign.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Marvel''s Spider-Man 2', 'https://arbcdn.techfast.vn/2d5a97a4ee094dd282e45329a92b8f67.webp', 'Marvel’s Spider-Man 2 is a triumphant step forward for Insomniac and superhero gaming.'),
((SELECT id FROM games_page WHERE page_index=7 LIMIT 1), 'Arma Reforger', 'https://arbcdn.techfast.vn/9e01446d086f4a03b5bd88b38b6689f6.webp', 'Arma Reforger is both an homage to the series’ origins and a forward-looking experiment in military simulation.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Dead Island 2', 'https://arbcdn.techfast.vn/32cf9147574347369e800157da465b3c.webp', 'Dead Island 2 doesn’t reinvent the zombie genre, but it perfects the art of zombie smashing. Its focus on melee combat, grotesque gore, and humorous setting make it a fun and chaotic experience, especially with friends.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'CookieRun: Kingdom', 'https://arbcdn.techfast.vn/3f3e26be23d340248735273dd1ac4b24.webp', 'Cookie Run: Kingdom is more than just a cute mobile game—it’s a cleverly designed blend of RPG depth, city-building strategy, and charming storytelling.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Forza Motorsport', 'https://arbcdn.techfast.vn/ff66a962184940c785f048eca5fa5a0c.webp', 'Forza Motorsport is a love letter to motorsport simulation, stripping away the casual festival atmosphere of Horizon in favor of pure, competitive track racing.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Call of Duty®: Black Ops 6', 'https://arbcdn.techfast.vn/04492dc178144cb0b877ace3adaa72c0.webp', 'Call of Duty: Black Ops 6 successfully cements itself as a worthy continuation of the Black Ops saga.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Forza Horizon 5', 'https://arbcdn.techfast.vn/f36417175fc94d639824147edfc4dab0.webp', 'Forza Horizon 5 is more than just a racing game - it is a celebration of cars, culture, and community. Its vibrant recreation of Mexico, diverse gameplay systems, and technical brilliance elevate it to new heights within the genre.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Grand Theft Auto: Vice City', 'https://arbcdn.techfast.vn/e0531dcb6b084d04b0dcba435305dc56.webp', 'Grand Theft Auto: Vice City is not just a game—it’s a time capsule. By blending stylish visuals, an unforgettable soundtrack, and groundbreaking freedom, Rockstar delivered an experience that shaped modern gaming.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'NBA 2K26', 'https://arbcdn.techfast.vn/478c423357f845f6a3259f371fd90e09.webp', 'NBA 2K26 is a new basketball game that delivers another powerful entry in the series, refining core mechanics while expanding story depth and social interactivity.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'FATAL FURY: City of the Wolves', 'https://arbcdn.techfast.vn/d1688e7ed20242c49ac5978ec657435c.webp', 'Fatal Fury: City of the Wolves delivers stunning cel-shaded visuals, strategic REV combat, and RPG-style solo modes—but fights guest cameo controversies and sparse content.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'Red Dead Redemption 2', 'https://arbcdn.techfast.vn/dd2a7d21ec364de0b8bee2b987eed477.webp', 'Red Dead Redemption 2 delivers an immersive open-world Western adventure with stunning visuals, rich storytelling, and deep gameplay mechanics.'),
((SELECT id FROM games_page WHERE page_index=8 LIMIT 1), 'VRChat', 'https://arbcdn.techfast.vn/40de9928ba064232854736975eee77dd.webp', 'VRChat is not a traditional video game. It is a social platform, creative canvas, and cultural phenomenon wrapped into one.');
INSERT INTO game_thumbnail (page_id, title, img, excerpt) VALUES
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'RuneScape: Dragonwilds', 'https://arbcdn.techfast.vn/af5e9c61f3e94d13b3ce689093ae160a.webp', 'RuneScape: Dragonwilds is an ambitious leap forward. While not without flaws, it successfully blends classic RuneScape identity with modern MMO expectations.'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'The Elder Scrolls IV: Oblivion Remastered', 'https://arbcdn.techfast.vn/e2f833a1270c43e1b5278b640846e55a.webp', 'The Elder Scrolls IV: Oblivion Remastered strikes a careful balance between nostalgia and modernization.'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Wuthering Waves', 'https://arbcdn.techfast.vn/9ca38620ce8d433c9d0e84fd7b42fec3.webp', 'Wuthering Waves is a bold, stylish RPG that pushes the boundaries of what a gacha title can offer'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Yu-Gi-Oh! Master Duel', 'https://arbcdn.techfast.vn/60ddb9acf22b4efb89ae3368f43c77c0.webp', 'Yu-Gi-Oh! Master Duel succeeds in bringing the beloved trading card game into the modern era with polish, depth, and accessibility'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Dude Theft Wars FPS Open world', 'https://arbcdn.techfast.vn/37b0263f34c84fc6af573225c7a9f077.webp', 'Dude Theft Wars excels on the strength of sheer absurdity. It distills sandbox fun into physics-driven chaos that feels refreshing and spontaneous'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Roblox: Dead Rails', 'https://arbcdn.techfast.vn/48fa16192cbe43f5abca104efa632cfb.webp', 'Roblox: Dead Rails transforms a familiar survival formula into a uniquely explosive experience: riding a train into the zombie apocalypse, scavenging fuel, fighting threats, and facing a final boss in a procedural Wild West nightmare'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'EA SPORTS FC™ 26', 'https://arbcdn.techfast.vn/0a2685c996b04bc7a665dcea70a7c9f1.webp', 'EA SPORTS FC™ 26 isn’t about grand spectacle—it’s about fine-tuning. Through deliberate enhancements—from tighter dribbling to dual-mode presets, and from narrative-rich Career features to inclusive competitive formats—it achieves a balanced evolution in football gaming'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'RimWorld: Odyssey', 'https://arbcdn.techfast.vn/8a388da701884d0fa9b83b7161a7348a.webp', 'A masterclass in big expansion strategy—expansive, imaginative, and technically impressive. Odyssey ensures RimWorld remains not just relevant, but essential.'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Grand Theft Auto VI', 'https://arbcdn.techfast.vn/b9d3cd49454e4246b66b6ba3aed36ed4.webp', 'Grand Theft Auto VI represents not just a new chapter for Rockstar but a turning point for the open-world genre'),
((SELECT id FROM games_page WHERE page_index=9 LIMIT 1), 'Schedule I', 'https://arbcdn.techfast.vn/4e4e0cb83f62429097bb283472623784.webp', 'Schedule I reinvents tycoon simulation with boldness, humor, and slick gameplay loops. Its success shows the power of indie creativity on a global stage');
COMMIT;
